targetRoom = city_01_antonsHood;
level = "boilercity";
msg = "Boiler City";
sprite_index = spr_gate_plage;
bgsprite = spr_gate_plageBG;
title_index = 8;
titlecard_index = 8;
title_music = "event:/music/w3/beachtitle";
group_arr = ["boilergroup"];