scr_initenemy();
usepalette = true;
stunfallspr = spr_babybear_stun;
walkspr = spr_babybear_walk;
scaredspr = spr_babybear_scared;
ragespr = spr_babybear_rage;
spr_dead = spr_babybear_dead;
paletteselect = 0;
spr_palette = palette_cheeseslime;
sprite_index = walkspr;
mask_index = spr_babybear_walk;
